version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - yamdb_api_database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: damarkevich/api_yamdb:latest
    restart: always
    volumes:
      - yamdb_api_static:/app/static/
      - yamdb_api_media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - yamdb_api_static:/var/html/static/
      - yamdb_api_media:/var/html/media/
    depends_on:
      - web

volumes:
  yamdb_api_database:
  yamdb_api_static:
  yamdb_api_media:
